# This is a sample build configuration for all languages.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
# image: samueldebruyn/debian-git


pipelines:
  custom: # Pipelines that are triggered manually
    sonar:
    - step:
        script:
          - git ftp push --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://ftp.melbrins.com/www/ 
  default:
    - step:
        script:
          - apt-get update
          - apt-get -qq install git-ftp
          - git config git-ftp.url "ftp://ftp.melbrins.com/www/"
          - git config git-ftp.user "$FTP_USERNAME"
          - git config git-ftp.password "$FTP_PASSWORD"
          - git ftp catchup
          - git ftp push